# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    datacenter: global  # In a HA setup, this would be global1 or global2

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# Settings related to the remote write feature.
remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db=prometheus"


# Settings related to the remote read feature.
remote_read:
  - url: "http://influxdb:8086/api/v1/prom/read?db=prometheus"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'federate'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="docker"}'
        
    static_configs:
      - targets:
        - 'prometheus-slave:9090'
